version: 2
updates:
  ## Authorization
  - directory: "backend/src/Altinn.Authorizationadmin/Altinn.Authorizationadmin"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  - directory: "backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Core"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  - directory: "backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Integration"
    package-ecosystem: "nuget"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"      

## Test
  - directory: "backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Persistance"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  - directory: "backend/src/Altinn.Authorizationadmin/Altinn.AuthorizationAdmin.Tests"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"


  
## Dockerfile
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 10
