version: "3.8"

services:
  backend:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: altinn-auth-admin_backend
    working_dir: /app/Altinn.Authorizationadmin/Altinn.Authorizationadmin
    command: ["dotnet", "watch", "run", "--no-launch-profile"]
    stop_signal: SIGKILL
    environment:
      - ASPNETCORE_URLS=http://+:5117
      - ASPNETCORE_ENVIRONMENT=Development
      - FRONTEND_MODE=Development
      - FRONTEND_DEV_URL=http://localhost:3000
      - PlatformSettings:BridgeApiEndpoint=http://local-bridge:5249/
    volumes:
      - type: bind
        source: ./backend/src
        target: /app
      - type: bind
        source: ~/.vsdbg
        target: /remote_debugger
        read_only: false
    networks:
      - altinn-auth-admin
    ports:
      - "5117:5117"

  local-bridge:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: altinn-auth-admin_local-bridge
    working_dir: /app/src/LocalBridge
    command: ["dotnet", "watch", "run", "--no-launch-profile"]
    stop_signal: SIGKILL
    environment:
      - ASPNETCORE_URLS=http://+:5249
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - type: bind
        source: ./development
        target: /app
      - type: bind
        source: ~/.vsdbg
        target: /remote_debugger
        read_only: false
    networks:
      - altinn-auth-admin
    ports:
      - "5249:5249"

  frontend:
    image: node:19-alpine
    container_name: altinn-auth-admin_frontend
    working_dir: /app
    command: ["sh", "-c", "yarn install --immutable && yarn dev --host"]
    environment:
      - VITE_BACKEND_API_URL=http://localhost:5117/api/
      - GITHUB_PACKAGES_PAT=${GITHUB_PACKAGES_PAT}
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    networks:
      - altinn-auth-admin
    ports:
      - "3000:3000"

networks:
  altinn-auth-admin:
    name: altinn-auth-admin
