name: Build frontend and copy dist-files
on:
  pull_request:
    paths-ignore:
      - '**.md'
  pull_request_target:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      release_type:
        description: "The type of release (one of 'patch' or 'minor')"
        required: true
        default: patch
        type: choice
        options:
        - patch
        - minor

jobs:
  build:
    name: Run frontend build
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: altinnadmin
          repo: altinn-access-management-frontend
          ref: main
          github_token: ${{ secrets.GITHUB_PAT }}
          workflow_file_name: build.yaml
          wait_interval: 10
          trigger_workflow: true
          wait_workflow: true
          propagate_failure: true
