name: Build and run unit tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: frontend
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
          
      - name: run ls 1
        working-directory: frontend/frontend
        run: ls    
      
      - name: install dependencies
        run: yarn install

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: run ls 2
        working-directory: frontend/frontend
        run: ls
          
      - name: run build
        working-directory: frontend/frontend
        run: yarn build
        
      - name: run tests
        working-directory: frontend/frontend
        run: yarn test
